### ISSUE TITLE
create a packages/types folder for all d.ts files 

### ISSUE THREAD

**Issue by sayandedotcom** [ixahmedxi/orbitkit#23]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ixahmedxi** [comment]
Why would you want to declare your own types and share it across the monorepo?

**Comment by sayandedotcom** [comment]
[types like next-auth types, etc .. check this. I am facing difficult to configure it ](https://github.com/calcom/cal.com/tree/71b0dd2aa36095b19ee56c7c13589e21ed915ad7/packages/types)

**Comment by ixahmedxi** [comment]
Typically you can avoid such scenarios by just putting these declarations where they are used and typescript would just pick it up when the file is imported, see here for example: https://github.com/ixahmedxi/orbitkit/blob/main/packages/auth/src/lucia.ts

**Comment by imCorfitz** [comment]
By creating a dedicated types package, you imply that you want to share the same types across all apps and packages. Conceptually that wouldn't be the best practice as you likely use packages differently in different apps. Take a package like [Auth.js](https://next-auth.js.org/getting-started/typescript#submodules) which relies on a types declaration file (`e.g. next-auth.d.ts`) in order to make the user or session object type safe. If you use `Auth.js` on both your admin dashboard app and your front-end app, you may not need to share the same properties in the user object for both apps.

For example, in your front-end app, you might want to include an avatar picture and points collected and in your admin dashboard a scope of privileges for what a user can access. 

That means that for your front-end app, your declaration file should look like this:

```ts
declare module "next-auth" {
  interface User {
    avatar: string
    points: number
  }
}
```

whereas in your admin dashboard app, it should look like this:

```ts
declare module "next-auth" {
  interface User {
    privileges: {
      read: boolean
      write: boolean
    }
  }
}
```
