### ISSUE TITLE
Bun support?

### ISSUE THREAD

**Issue by duttaoindril** [ixahmedxi/orbitkit#50]
**Is your feature request related to a problem? Please describe.**
I want to use bun, instead of pnpm. I've been able to completely get rid of .js files by using bun.

**Describe the solution you'd like**
pnpm -> bun, or at least as an option

**Describe alternatives you've considered**
pnpm

**Additional context**

**Comment by ixahmedxi** [comment]
The problem with bun currently is that in monorepo settings it does not have the feature set that pnpm does have. for example, in bun you can't do `--filter` and run scripts in packages, you actually need to cd into the package and then run the scripts.

I use bun for every non monorepo codebase nowadays, otherwise I still use pnpm.

**Comment by ixahmedxi** [comment]
I am still going to hold of bun as the package manager support for a while until it becomes on par with pnpm for workspaces.
