### ISSUE TITLE
A CLI

### ISSUE THREAD

**Issue by kareemmahlees** [ixahmedxi/orbitkit#56]
**Is your feature request related to a problem? Please describe.**
As per [docs](https://orbitkit.dev/installation#installation), Orbitkit requires manual setup and installation which seems an excellent scenario for a CLI!

**Describe the solution you'd like**
A CLI, inspired by [create-t3-app](https://github.com/t3-oss/create-t3-app), that performs the same exact steps ( at least for know ) mentioned in the installation section.

**Describe alternatives you've considered**
N/A

**Additional context**
This feature is related to #21, although achieving the desired outcome mentioned in the issue will require notable changes in how the repo is structured ( or not! ).
As for now the CLI can just perform the manual steps of installation, and in the future additional features and decisions could be made.
If this is acceptable I can gladly make a PR for it!

**Comment by cowboycodr** [comment]
Considering that (aside from configuring .env variables) it is only two steps. Cloning, and installing dependencies. I don't really think it is necessary and I believe better time can be spend working on OrbitKit itself.

I left out configuring .env variables because often times you might start your project (or at least clone it) before you have all of your .env variables configured.

That being said it would definitely be helpful. Probably just not worth time time.

**Comment by ixahmedxi** [comment]
It would be nice to have in the far future, but i think the main objective now is to get the starterkit complete.

**Comment by kareemmahlees** [comment]
Seems reasonable.
Will close this for now, feel free to reopen it whenever you see the time fits to tackle it.
